### ISSUE TITLE
NL data can not be imported anymore

### ISSUE THREAD

**Issue by dtroelofsprins** [molgenis/molgenis-py-bbmri-eric#61]
The import of NL collections into the staging area fails, due to the fact that there are more than 1000 rows AND a parent collection has a 'higher' ID than the sub collection where it is referenced in. The parent collection therefore ends up in the second batch of 1000 rows to be uploaded, and therefore the upload of the sub collection which is in the first batch fails.

**Comment by tommydeboer** [comment]
Fixed in #62
